server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /data/meshmap.net/website;
    location /api/ {
        proxy_pass https://mqtt-request.meshhessen.de/api/;
        proxy_set_header Host mqtt-request.meshhessen.de;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
        index index.html;
        try_files $uri $uri/ =404;
        add_header Cache-Control "public, max-age=60";
        add_header Vary "Accept-Encoding";
    }
}
